---
title: "Fintech3_Project2"
author: "Aditya Sharma"
date: "2024-03-01"
output: html_document
---

# Calculating the duration of a bond 

```{r}

library(rootSolve)

# duration is the measure of the bond's sensitivity to interest rate changess

# convexity, higher convexity means bond price more sensitiy, curve is steeper moves are more drastic 

calculate_bond_duration_and_convexity <- function(coupon_rate, years_to_maturity, yield_to_maturity) {

  present_values <- numeric(years_to_maturity)
  for (i in 1:years_to_maturity) {
    present_values[i] <- coupon_rate * (1 - (1 + yield_to_maturity)^-(years_to_maturity - i + 1)) / yield_to_maturity
  }
  present_values[years_to_maturity] <- present_values[years_to_maturity] + (1 / (1 + yield_to_maturity)^years_to_maturity)
  
  # Cal duration 
  
  durations <- numeric(years_to_maturity)
  for (i in 1:years_to_maturity) {
    durations[i] <- (present_values[i] * i) / sum(present_values)
  }
  
  # Calculate bond duration
  
  bond_duration <- sum(durations)
  
  # Calculate convexity
  
  convexity <- numeric(years_to_maturity)
  for (i in 1:years_to_maturity) {
    convexity[i] <- (present_values[i] * i * (i + 1)) / sum(present_values)
  }
  bond_convexity <- sum(convexity) / ((1 + yield_to_maturity)^2)
  
  return(list(bond_duration = bond_duration, bond_convexity = bond_convexity))
}

# user inputs 

coupon_rate <- 0.05  # inputs 
years_to_maturity <- 5 # inputs 
yield_to_maturity <- 0.06  # inputs 

# cal duration and convexity 

result <- calculate_bond_duration_and_convexity(coupon_rate, years_to_maturity, yield_to_maturity)

print(paste("Bond duration:", result$bond_duration))
print(paste("Bond convexity:", result$bond_convexity))

```

# Calculating the duration of a portfolio of bonds

```{r}

# duration and face value of bonds 
amounts <- c(1000, 1500)  # face value 
durations <- c(3, 5)      # duration 


# Portfolio Duration Function 

portfolio_duration <- function(amounts, durations) {
  weighted_sum <- sum(amounts * durations)
  total_amount <- sum(amounts)
  portfolio_duration <- weighted_sum / total_amount
  return(portfolio_duration)
}

```

# (YTM) of a bond - WORK IN PROGRESS 

```{r}

calculate_YTM <- function(price, face_value, coupon_payment, years_to_maturity, frequency = 1) {

  present_value <- function(rate, price, face_value, coupon_payment, years_to_maturity, frequency) {
    periods <- years_to_maturity * frequency
    coupon <- coupon_payment * (frequency / 2)  
    
    # PV coupon
    
    pv_coupons <- sum(coupon / (1 + rate/frequency)^(1:periods))
    
    # PV face value 
    
    pv_face_value <- face_value / (1 + rate/frequency)^periods
    
    # total PV 
    
    pv_total <- pv_coupons + pv_face_value
    
    # difference of bond price and present value 
    
    diff <- price - pv_total
    
    return(diff)
  }
  
  # (YTM) 
  ytm <- uniroot(present_value, 
                 interval = c(0, 1),
                 price = price, 
                 face_value = face_value,
                 coupon_payment = coupon_payment,
                 years_to_maturity = years_to_maturity, 
                 frequency = frequency)$root
  
  return(ytm * frequency * 100)  # YTM to percentage
}

# user inputs 
price <- 950   # current price 
face_value <- 1000  # FV
coupon_payment <- 50  # annual coupon 
years_to_maturity <- 5  # years to mat 
frequency <- 2  # number of coupon payments  


ytm <- calculate_YTM(price, face_value, coupon_payment, years_to_maturity, frequency)
cat("Yield to Maturity (YTM):", ytm, "%\n")


```

